---

- name: readiness/post_deploy | re-enable systemd__disable_apt_services
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item.svc }}"
    enabled: true
    state: started
    daemon_reload: true
    no_block: true
  register: r__systemd__enable_apt_services
  delegate_to: "{{ item.hostname }}"
  with_items: |-
    {%- set ns = namespace(res=[]) -%}
    {%- for host in cluster_hosts_target -%}
      {%- for svc in hostvars[host.hostname]['systemd__disable_apt_services'] | default([]) | json_query('[?changed==`true`].name') -%}
        {%- set ns.res = ns.res + [{'hostname': host.hostname, 'svc': svc}] -%}
      {%- endfor -%}
    {%- endfor -%}
    {{ ns.res }}
