---

- name: clean/gcp | clean vms
  block:
    - name: clean/gcp | Remove deletion protection
      google.cloud.gcp_compute_instance:
        auth_kind: "serviceaccount"
        service_account_contents: "{{cluster_vars[buildenv].gcp_service_account_contents}}"
        project: "{{cluster_vars[buildenv].vpc_project_id}}"
        name: "{{item.name}}"
        zone: "{{ item.regionzone }}"
        deletion_protection: 'no'
      with_items: "{{ hosts_to_clean }}"
      when: cluster_vars[buildenv].deletion_protection | bool

    - name: clean/gcp | Delete VMs
      google.cloud.gcp_compute_instance:
        auth_kind: "serviceaccount"
        service_account_contents: "{{cluster_vars[buildenv].gcp_service_account_contents}}"
        project: "{{cluster_vars[buildenv].vpc_project_id}}"
        name: "{{item.name}}"
        zone: "{{ item.regionzone }}"
        state: "absent"
      with_items: "{{ hosts_to_clean }}"
      register: r__gcp_compute_instance
      async: 7200
      poll: 0

    - name: clean/gcp | Wait for VM deletion to complete
      async_status: { jid: "{{ item.ansible_job_id }}" }
      register: async_jobs
      until: async_jobs is finished
      retries: 300
      with_items: "{{r__gcp_compute_instance.results}}"

    - name: clean/gcp | Get any attached static IPs
      google.cloud.gcp_compute_address_info:
        auth_kind: "serviceaccount"
        service_account_contents: "{{cluster_vars[buildenv].gcp_service_account_contents}}"
        project: "{{cluster_vars[buildenv].vpc_project_id}}"
        region: "{{cluster_vars.region}}"
        filters:
          - address = "{{ item.ipv4.public }}"
      with_items: "{{ hosts_to_clean }}"
      register: r__gcp_compute_address_info

    - name: clean/gcp | r__gcp_compute_address_info
      debug: msg={{ r__gcp_compute_address_info }}

    - name: clean/gcp | Delete static IPs (if any were found)
      google.cloud.gcp_compute_address:
        auth_kind: "serviceaccount"
        service_account_contents: "{{cluster_vars[buildenv].gcp_service_account_contents}}"
        project: "{{cluster_vars[buildenv].vpc_project_id}}"
        region: "{{cluster_vars.region}}"
        name: "{{ item.name }}"
        state: absent
      loop: "{{ r__gcp_compute_address_info.results | json_query(\"[].resources[]\") }}"
  when: hosts_to_clean | length > 0


- name: clean/gcp | clean networking (when '-e clean=_all_')
  block:
    - name: clean/networking/gcp | Delete GCP cluster firewalls
      google.cloud.gcp_compute_firewall:
        auth_kind: "serviceaccount"
        service_account_contents: "{{cluster_vars[buildenv].gcp_service_account_contents}}"
        project: "{{ cluster_vars[buildenv].vpc_host_project_id or cluster_vars[buildenv].vpc_project_id }}"    # Use the shared vpc host project if defined, else use the vpc project
        name: "{{ item.name }}"
        state: "absent"
      with_items: "{{ cluster_vars.firewall_rules }}"

    - name: clean/gcp | Delete the GCP network and its dependencies (if -e delete_gcp_network_on_clean=true)
      block:
        - name: clean/gcp | Get the GCP network routes (if -e delete_gcp_network_on_clean=true)
          google.cloud.gcp_compute_route_info:
            auth_kind: "serviceaccount"
            service_account_contents: "{{cluster_vars[buildenv].gcp_service_account_contents | string}}"   # NOTE: We need to cast this vault-derived variable to a string so that the register variable doesn't obfuscate the secret values, which then can't be used in later tasks.
            project: "{{ cluster_vars[buildenv].vpc_host_project_id or cluster_vars[buildenv].vpc_project_id }}"    # Use the shared vpc host project if defined, else use the vpc project
            filters:
              - destRange = "0.0.0.0/0"
          register: r__gcp_compute_routes

        - debug: msg="{{ r__gcp_compute_routes }}"

        - name: clean/gcp | Delete the GCP network routes (if -e delete_gcp_network_on_clean=true)
          google.cloud.gcp_compute_route:
            auth_kind: "serviceaccount"
            service_account_contents: "{{cluster_vars[buildenv].gcp_service_account_contents}}"
            project: "{{ cluster_vars[buildenv].vpc_host_project_id or cluster_vars[buildenv].vpc_project_id }}"    # Use the shared vpc host project if defined, else use the vpc project
            name: "{{item.name}}"
            network: {'selfLink': "{{item.network}}"}
            dest_range: "{{item.destRange}}"
            state: absent
          with_items: "{{ r__gcp_compute_routes.resources }}"

        - name: clean/gcp | Delete the GCP network (if -e delete_gcp_network_on_clean=true)
          google.cloud.gcp_compute_network:
            auth_kind: "serviceaccount"
            service_account_contents: "{{cluster_vars[buildenv].gcp_service_account_contents}}"
            project: "{{ cluster_vars[buildenv].vpc_host_project_id or cluster_vars[buildenv].vpc_project_id }}"    # Use the shared vpc host project if defined, else use the vpc project
            name: "{{cluster_vars[buildenv].vpc_network_name}}"
            state: absent
      when: delete_gcp_network_on_clean is defined and delete_gcp_network_on_clean|bool
  when: clean is defined and clean == '_all_'
